# Generated by Django 2.2.5 on 2020-01-29 20:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileImage',
            new_name='Profile',
        ),
        migrations.DeleteModel(
            name='ProfileInfo',
        ),
    ]
