# Generated by Django 2.2.5 on 2020-01-28 05:08

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200127_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(default='Test'),
            preserve_default=False,
        ),
    ]
