# Generated by Django 2.2.5 on 2020-02-01 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200201_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='postview',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='postview',
            name='ip',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='postview',
            name='session',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
