# Generated by Django 2.2.5 on 2020-02-01 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200201_1418'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostView',
        ),
    ]
