# Generated by Django 2.2.5 on 2020-01-26 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'Property', 'verbose_name_plural': 'Properties'},
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('For Rent', 'For Rent'), ('For Sale', 'For Sell')], default=1, max_length=200),
            preserve_default=False,
        ),
    ]
