# Generated by Django 2.2.5 on 2020-01-26 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_auto_20200126_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='rooms',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('For Rent', 'For Rent'), ('For Sale', 'For Sell')], max_length=501),
        ),
        migrations.AlterField(
            model_name='propertyimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='property/%Y/%m/%d/'),
        ),
    ]
