# Generated by Django 2.2.5 on 2020-01-26 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_property_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(choices=[('Plots', 'Plots'), ('Lands', 'Lands'), ('Apartments', 'Apartments'), ('Frames', 'Frames'), ('Auto-Mobiles', 'Auto-Mobiles'), ('Houses', 'Houses'), ('Commercial', 'Commercial')], max_length=50),
        ),
    ]
