# Generated by Django 2.2.5 on 2020-01-27 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_auto_20200126_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('For Rent', 'For Rent'), ('For Sale', 'For Sale')], max_length=501),
        ),
    ]
