# Generated by Django 2.2.5 on 2020-02-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_auto_20200201_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(choices=[('Lands', 'Lands'), ('Apartments', 'Apartments'), ('Commercials', 'Commercials'), ('Vehicles', 'Vehicles')], max_length=50),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='title',
            field=models.CharField(choices=[('Plot', 'Plot'), ('Farm', 'Farm'), ('Apartment', 'Apartment'), ('House', 'House'), ('Room', 'Room'), ('Hostel', 'Hostel'), ('Office Place', 'Office Place'), ('Car', 'Car'), ('Motorcycle', 'Motorcycle'), ('Bajaji', 'Bajaji')], max_length=50),
        ),
    ]
