# Generated by Django 2.2.5 on 2020-02-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20200201_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='title',
            field=models.CharField(choices=[('Plot', 'Plot'), ('Farm', 'Farm'), ('Apartment', 'Apartment'), ('House', 'House'), ('Room', 'Room'), ('Hostel', 'Hostel'), ('Office Place', 'Office Place'), ('Frame', 'Frame'), ('Car', 'Car'), ('Motorcycle', 'Motorcycle'), ('Bajaji', 'Bajaji')], max_length=50),
        ),
    ]
